In [1]:
import numpy as np

a = np.array([1,2,3])

a

array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
np.shape(a)

(3,)

In [4]:
a[1]

2

In [7]:
# Matrices

In [16]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
b.shape

(3, 3)

In [10]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
d = np.ones((4,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
f = np.full((5,2),7)
f

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [17]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
g = b[1:, 1:]
g

array([[5, 6],
       [8, 9]])

In [21]:
g2 = b[:2, :2]
g2

array([[1, 2],
       [4, 5]])

In [22]:
x = np.array([
    [1,2],
    [3,4]
],
dtype = np.float64)

y = np.array([
    [5,6],
    [7,8]
],
dtype = np.float64)
print(x)
print(y)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [23]:
print('sum of matrix \n {} y \n {} is : '.format(x, y, x+y))

sum of matrix 
 [[1. 2.]
 [3. 4.]] y 
 [[5. 6.]
 [7. 8.]] is : 


In [24]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [25]:
comp = x+y == np.add(x,y)
comp

array([[ True,  True],
       [ True,  True]])

In [26]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [27]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [28]:
np.sum(x, axis=1)

array([3., 7.])

In [29]:
x

array([[1., 2.],
       [3., 4.]])

In [30]:
np.sum(x, axis=0)

array([4., 6.])